#!/usr/bin/env python3
"""Persistent test: create sandbox, write a marker file inside, STOP (not delete).

Same end-to-end path as test_sandbox.py, but instead of deleting the sandbox at
the end, writes a HELLO_AZURE_DEPLOYMENT.txt file inside the sandbox with
deployment metadata, then stops (preserves) the sandbox.

After this test, you can inspect the sandbox via the Daytona dashboard:
  1. Start the sandbox from the dashboard
  2. Open a terminal or use the file browser
  3. Read /workspace/HELLO_AZURE_DEPLOYMENT.txt (or wherever cwd was)

When you're done, delete the sandbox manually from the dashboard, or run
test_sandbox.py to confirm a fresh end-to-end run can still create + delete.
"""
from __future__ import annotations

import datetime
import os
from urllib.parse import urlparse

from daytona import Daytona, DaytonaConfig

from _helpers import (
    assert_self_hosted,
    code_run_via_proxy,
    fail,
    load_test_env,
    setup_ssl_skip_if_requested,
)

MARKER_FILENAME = "HELLO_AZURE_DEPLOYMENT.txt"


def main() -> "None":
    load_test_env()
    setup_ssl_skip_if_requested()

    api_url = os.environ.get("DAYTONA_API_URL", "").rstrip("/")
    api_key = os.environ.get("DAYTONA_API_KEY", "")
    target = os.environ.get("DAYTONA_TARGET", "us")

    if not api_url:
        fail("DAYTONA_API_URL is not set (see .env.example)")
    if not api_key or api_key == "replace-me-from-dashboard":
        fail("DAYTONA_API_KEY is not set — generate one in the dashboard")
    api_host = assert_self_hosted(api_url)

    print(f"=== PERSISTENT TEST against {api_url} ===")
    print(f"Target/region: {target}\n")

    config = DaytonaConfig(api_key=api_key, api_url=api_url, target=target)
    client = Daytona(config)

    print("[1/5] Creating sandbox...")
    sandbox = client.create()
    print(f"  id={sandbox.id}")
    print(f"  state={getattr(sandbox, 'state', 'unknown')}\n")

    timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat()
    marker_body = (
        "=" * 60 + "\n"
        "HELLO FROM AZURE-DEPLOYED DAYTONA OSS\n"
        + "=" * 60 + "\n\n"
        f"Sandbox ID:   {sandbox.id}\n"
        f"Deployment:   {api_url}\n"
        f"Written at:   {timestamp}\n"
        f"Host header:  {api_host}\n\n"
        "If you can read this file from inside this sandbox, the entire\n"
        "self-hosted flow works end-to-end:\n"
        "  SDK -> api -> proxy -> runnermanager -> runner -> sandbox\n\n"
        "Generated by test_sandbox_keep.py\n"
        + "=" * 60 + "\n"
    )

    print(f"[2/5] Writing marker file '{MARKER_FILENAME}' inside the sandbox...")
    write_code = (
        "import os\n"
        f"content = {marker_body!r}\n"
        f"path = {MARKER_FILENAME!r}\n"
        "with open(path, 'w') as f:\n"
        "    f.write(content)\n"
        "print('Written:', os.path.abspath(path), '(', len(content), 'bytes )')\n"
    )
    out = code_run_via_proxy(sandbox, api_url, write_code)
    print(f"  {out}\n")

    print("[3/5] Reading marker back from sandbox to verify it persisted...")
    read_code = (
        f"path = {MARKER_FILENAME!r}\n"
        "with open(path) as f:\n"
        "    content = f.read()\n"
        "print('---marker contents follow---')\n"
        "print(content)\n"
    )
    out = code_run_via_proxy(sandbox, api_url, read_code)
    print(out)
    if "HELLO FROM AZURE-DEPLOYED DAYTONA OSS" not in out:
        fail("marker file content mismatch — write/read cycle failed")
    print()

    print("[4/5] Running uname so you can confirm the runner OS...")
    uname_out = code_run_via_proxy(sandbox, api_url, "import os; print(os.uname())")
    print(f"  uname: {uname_out}\n")

    print("[5/5] Stopping (NOT deleting) sandbox so you can inspect it later...")
    sandbox.stop()
    print(f"  stopped {sandbox.id}\n")

    dashboard_url = api_url.rsplit("/api", 1)[0] + "/dashboard"
    print("=" * 60)
    print("PASS - sandbox is stopped but preserved.")
    print("=" * 60)
    print(f"\nInspect via the dashboard:")
    print(f"  Dashboard:  {dashboard_url}")
    print(f"  Sandbox ID: {sandbox.id}")
    print(f"  Marker:     {MARKER_FILENAME} in the sandbox workspace\n")
    print("To restart, open the sandbox in the dashboard and click Start.")
    print("To delete entirely, use the dashboard's delete action.\n")


if __name__ == "__main__":
    main()
